
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_EN_CLK25_GPIO_DEVICE_ID,
		XPAR_EN_CLK25_GPIO_BASEADDR,
		XPAR_EN_CLK25_GPIO_INTERRUPT_PRESENT,
		XPAR_EN_CLK25_GPIO_IS_DUAL
	},
	{
		XPAR_LEV_SHIFT_GPIO_DEVICE_ID,
		XPAR_LEV_SHIFT_GPIO_BASEADDR,
		XPAR_LEV_SHIFT_GPIO_INTERRUPT_PRESENT,
		XPAR_LEV_SHIFT_GPIO_IS_DUAL
	},
	{
		XPAR_MISC_LVDS_GPIO_DEVICE_ID,
		XPAR_MISC_LVDS_GPIO_BASEADDR,
		XPAR_MISC_LVDS_GPIO_INTERRUPT_PRESENT,
		XPAR_MISC_LVDS_GPIO_IS_DUAL
	},
	{
		XPAR_QSPI_GPIO_DEVICE_ID,
		XPAR_QSPI_GPIO_BASEADDR,
		XPAR_QSPI_GPIO_INTERRUPT_PRESENT,
		XPAR_QSPI_GPIO_IS_DUAL
	}
};


